name: flutter_localization_translator
description: The package helps developers easily translate .arb resources into different languages.
repository: https://github.com/tokyolem/flutter_localization_translator
homepage: https://pub.dev/packages/flutter_localization_translator
license: MIT
version: 0.0.4
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.3.0

dependencies:
  translator: ^1.0.0
  yaml: ^3.1.2